language: cpp

os:
  - linux
  - osx
osx_image: xcode9

compiler:
  - g++
  - clang

cache:
  - ccache: true

dist: trusty
sudo: false

addons:
  apt:
    sources:
      # sources list: https://github.com/travis-ci/apt-source-whitelist/blob/master/ubuntu.json
      - llvm-toolchain-trusty-4.0
      - ubuntu-toolchain-r-test
    packages:
      # packages list: https://github.com/travis-ci/apt-package-whitelist/blob/master/ubuntu-precise
      - g++-5
      - clang-4.0


install:
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew update > /dev/null
      brew install ccache

      # ccache
      PATH="/usr/local/opt/ccache/libexec:$PATH"
    else
      # gcc
      if [ "$CXX" = "g++" ]; then
        CXX="ccache g++-5"
      else
        CXX="ccache clang++-4.0"
      fi
    fi
  - git submodule update --init --remote --recursive

script:
  - cd "$TRAVIS_BUILD_DIR/test"
  - make -j2
  - ./run_tests
